### ISSUE TITLE
Problem regarding the baseline mode (standard attention model)

### ISSUE THREAD

**Issue by memray** [mast-group/convolutional-attention#2]
Hi there,

I really like your work and I'm trying to work out something based on your project.
I saw your paper mention that you used another baseline model, which is a standard attention model (Bahdanau et al., 2015) with biRNN and fully connected components. But I didn't see the source code in your project here.

Would you please help me with it?

Thanks,
Rui

**Comment by mallamanis** [comment]
Hi Rui,
Thanks for your interest :) I believe we used the code https://github.com/lisa-groundhog/GroundHog/tree/master/experiments/nmt for the biRNN model. Does this help?

**Comment by memray** [comment]
Cool, that's what I want. I thought the rnn code is also included in this project :)
Thanks!
