### ISSUE TITLE
Error occur in runing baseline.py

### ISSUE THREAD

**Issue by SantiagoMunz** [mast-group/convolutional-attention#3]
TypeError                                 Traceback (most recent call last)
D:\Project\convolutional-attention-master\convolutional_attention\baseline.py in <module>()
     85             res = [token_precision_recall(name, real_name) for name in suggested_names]
     86             is_correct = [len(real_name) == len(name) and all(k == l for k, l in zip(name, real_name)) for name in suggested_names]
---> 87             eval.add_result([1.] * num_ranks , is_correct, [False] * num_ranks, res)
     88     print ''
     89     print eval

TypeError: add_result() takes exactly 6 arguments (5 given)

**Comment by mallamanis** [comment]
Thanks for this, you're indeed right. The signature of `add_result()` is different.

As you can see it accepts 
```python
def add_result(self, confidence, is_correct, is_unk, precision_recall, unk_word_accuracy):
```

Please, feel free to submit a pull request fixing this.
