### ISSUE TITLE
Error while executing conv_att_rec_learner.py

### ISSUE THREAD

**Issue by sawan16** [mast-group/convolutional-attention#4]
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Extracting data...
/home/sawan/convnet/convolutional-attention-master/convolutional_attention/conv_att_rec_model.py:133: UserWarning: The `image_shape` keyword argument to `tensor.nnet.conv2d` is deprecated, it has been renamed to `input_shape`.
  filter_shape=self.conv_layer1_code.get_value().shape)
/home/sawan/convnet/convolutional-attention-master/convolutional_attention/conv_att_rec_model.py:138: UserWarning: The `image_shape` keyword argument to `tensor.nnet.conv2d` is deprecated, it has been renamed to `input_shape`.
  filter_shape=self.conv_layer2_code.get_value().shape)
/home/sawan/convnet/convolutional-attention-master/convolutional_attention/conv_att_rec_model.py:152: UserWarning: The `image_shape` keyword argument to `tensor.nnet.conv2d` is deprecated, it has been renamed to `input_shape`.
  filter_shape=self.conv_layer3_code.get_value().shape)[:, 0, :, 0]
Traceback (most recent call last):
  File "convolutional_attention/conv_att_rec_learner.py", line 235, in <module>
    model.train(input_file, max_epochs=max_num_epochs)
  File "convolutional_attention/conv_att_rec_learner.py", line 35, in train
    self.naming_data.name_empirical_dist)
  File "/home/sawan/convnet/convolutional-attention-master/convolutional_attention/conv_att_rec_model.py", line 18, in __init__
    self.__init_parameter(empirical_name_dist)
  File "/home/sawan/convnet/convolutional-attention-master/convolutional_attention/conv_att_rec_model.py", line 88, in __init_parameter
    self.__compile_model_functions()
  File "/home/sawan/convnet/convolutional-attention-master/convolutional_attention/conv_att_rec_model.py", line 227, in __compile_model_functions
    self.grad_step = theano.function(inputs=[], updates=step_updates, outputs=ratios)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 208, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=sentence_count, shared_var.type=TensorType(float64, scalar), update_val=Alloc.0, update_val.type=TensorType(float64, (True,))).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by mallamanis** [comment]
Hi, did you set the environment variable/config to `THEANO_FLAGS=floatX=float32`?

**Comment by sawan16** [comment]
I haven't created .theanorc file to set flags. I have executed same code on my PC by making virtual env.  Execution completed successfully. Now I want to run it on the whole dataset, so I tried on my institute's server machine(ubuntu).  Here I am getting this error.

**Comment by mallamanis** [comment]
This suggests that there is a difference in the setup. If you run
```
THEANO_FLAGS=floatX=float32 python path/to/file.py ...
```
this should probably do it. But in any case, please try looking at how the two different environments differ to debug this issue.

**Comment by sawan16** [comment]
Sorry Sir, I was able to run **copy_conv_rec_learner.py** on my PC. When I executed **conv_att_rec_learner.py** then the error generated.  The error is still there, even after using the THEANO_FLAG option.

**Comment by sawan16** [comment]
Now, I am able to execute it.  [executed on google colab]
Update done by me:
file: conv_att_rec_model.py
line no. 227
step_updates.append((grad_acc[-1],  T.zeros(1,dtype=floatX)))
T.zeros(1,dtype=floatX) replaced with 0
new code
step_updates.append((grad_acc[-1],  0))
Thanks
