### ISSUE TITLE
Predicting takes longer than training

### ISSUE THREAD

**Issue by chfeiler** [mast-group/convolutional-attention#5]
Hello!

I used the model in `copy_conv_rec_learner.py` in order to train on the method names of round about 160000 methods. The [training](https://github.com/mast-group/convolutional-attention/blob/master/convolutional_attention/copy_conv_rec_learner.py#L295) for 30 epochs took round about a day. However, the [calculation of the scores](https://github.com/mast-group/convolutional-attention/blob/master/convolutional_attention/copy_conv_rec_learner.py#L309) after the model was saved wasn't finished after 8 hours. The validation dataset covered less than 20000 methods.

The `json`-files were structured acording to the description [here](http://groups.inf.ed.ac.uk/cup/codeattention/dataset.txt):
```
[
  {"tokens":["<SENTENCE_START>","{","return","project","params",";","}","<SENTENCE_END/>"], "name":["get","project","params"]},
  ...
]
```

Therefore my question: is the input json file wrong or is it normal for the scoring to take that long?

Thanks in advance!

**Comment by mallamanis** [comment]
Hi @chfeiler , I cannot be sure why this is the problem, but I suspect that it has to do with something of the following:

* The beam search has a big-ish size. Try reducing this.
* The model was either not trained well or it did not learn almost anything. This results in very long output sequences.
* Some other bug where the decoding gets stuck on a single example.

The JSON format seems correct to me. Can you try to computing the score in a small subset of your original set? Does this behavior persist?

**Comment by chfeiler** [comment]
Hi @mallamanis , thanks for the quick response!

Probably it's no bug but the other points you mentioned...
On a small subset the behavior persisted (on a less performant machine: >5min per prediction).
With a smaller beam width it works better.
Just to make sure:
The beam width is reduced by adopting `max_steps` in [this method](https://github.com/mast-group/convolutional-attention/blob/master/convolutional_attention/copy_conv_rec_learner.py#L133), isn't it?

**Comment by mallamanis** [comment]
It's been some time since I coded this...

I think it is `max_size_to_keep` [here](https://github.com/mast-group/convolutional-attention/blob/master/convolutional_attention/copy_conv_rec_learner.py#L153). 

It's a bit confusing, because this code doesn't exactly implement beam search (although it should) but a hybrid. I suggest that you reduce both `max_steps` and `max_size_to_keep` and see how this goes...

**Comment by chfeiler** [comment]
Haha I understand:)

Ok thank you!
