### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by s1530129650** [mast-group/convolutional-attention#6]
OS: Ubuntu
  command: python copy_conv_rec_learner.py model 10 128 test_result

```
  File "copy_conv_rec_learner.py", line 11, in <module>
      from experimenter import ExperimentLogger
  ImportError: No module named experimenter
```

**Comment by mallamanis** [comment]
Hi, install https://github.com/mallamanis/experimenter or remove the relevant code. This is not needed for the task
